<a href="https://colab.research.google.com/github/oriidearmstrong/Capstone/blob/main/Capstone_Project_Oriide_Armstrong.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import itertools
import pandas as pd
import numpy as np
import matplotlib.ticker as ticker
from sklearn import preprocessing
%matplotlib inline

In [2]:
import os 
os.getcwd()

'/content'

In [14]:
from google.colab import files
files.upload()

Saving global_table.csv to global_table.csv


{'global_table.csv': b'\xef\xbb\xbfName,WHO Region,Cases - cumulative total,Cases - cumulative total per 100000 population,Cases - newly reported in last 7 days,Cases - newly reported in last 7 days per 100000 population,Cases - newly reported in last 24 hours,Deaths - cumulative total,Deaths - cumulative total per 100000 population,Deaths - newly reported in last 7 days,Deaths - newly reported in last 7 days per 100000 population,Deaths - newly reported in last 24 hours\r\nUnited States of America,Americas,35010407,10577.08,618994,187.01,78722,609022,183.99,2759,0.83,387\r\nBrazil,Americas,19953501,9387.26,245839,115.66,15143,557223,262.15,6721,3.16,389\r\nArgentina,Americas,4947030,10945.78,87860,194.4,11183,106045,234.63,1940,4.29,273\r\nColombia,Americas,4801050,9435.49,64701,127.16,6636,121216,238.23,2034,4,218\r\nMexico,Americas,2861498,2219.37,107060,83.04,6506,241279,187.14,2684,2.08,245\r\nPeru,Americas,2114445,6412.88,9440,28.63,1244,196518,596.02,545,1.65,80\r\nChile,America

In [16]:
import pandas as pd
import numpy as np

In [17]:
data = pd.read_csv("global_table.csv")
data.head()

Name  ... Deaths - newly reported in last 24 hours
0  United States of America  ...                                      387
1                    Brazil  ...                                      389
2                 Argentina  ...                                      273
3                  Colombia  ...                                      218
4                    Mexico  ...                                      245

[5 rows x 12 columns]

In [18]:
data.describe()

Cases - cumulative total  ...  Deaths - newly reported in last 24 hours
count              5.600000e+01  ...                                 56.000000
mean               1.387297e+06  ...                                 34.928571
std                5.364471e+06  ...                                 89.166006
min                7.000000e+00  ...                                  0.000000
25%                2.438750e+03  ...                                  0.000000
50%                2.071600e+04  ...                                  0.500000
75%                3.888312e+05  ...                                 11.250000
max                3.501041e+07  ...                                389.000000

[8 rows x 10 columns]

In [19]:
import matplotlib.pyplot as plt
import numpy as np
from sklearn.linear_model import LinearRegression 
%matplotlib inline

In [20]:
%%capture
! pip install seaborn

In [21]:
X = data[['Cases - cumulative total']] 
Y = data['Deaths - cumulative total'] 
lm = LinearRegression() 
lm 
lm.fit(X,Y)
lm.score(X, Y)

0.879731556925817

In [23]:
X = data[['Cases - cumulative total']] 
Y = data['Deaths - cumulative total'] 
lm = LinearRegression()
lm
lm.fit(X,Y)

Yhat=lm.predict(X)
Yhat[0:5]

array([715801.38585336, 411379.48842034, 107977.29041276, 105025.85347165,
        65811.81441143])

In [24]:
lm.intercept_

7957.78711918573

In [25]:
lm.coef_

array([0.02021809])

In [51]:
lm.fit(X,Y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [29]:
X = data[['Cases - newly reported in last 7 days']]
Y = data['Deaths - cumulative total'] 
lm1 = LinearRegression() 
lm1 
lm1.fit(X,Y)
lm1.score(X, Y)

0.8108246066545549

In [30]:
lm.fit(X, Y)
print('The R-square is: ', lm.score(X, Y))

The R-square is:  0.8108246066545549


In [52]:
Yhat=lm.predict(X)
print('The output of the first four predicted value is: ', Yhat[0:4])

The output of the first four predicted value is:  [728144.36762597 294678.44716355 111166.19984345  84264.1423821 ]


In [53]:
from sklearn.metrics import mean_squared_error

In [54]:
mse = mean_squared_error(data['Deaths - cumulative total'], Yhat)
print('The mean square error of cumulative death and predicted value is: ', mse)

The mean square error of cumulative death and predicted value is:  2484410001.1993213


In [40]:
Z = data[['Cases - cumulative total', 'Cases - newly reported in last 7 days']]

In [41]:
lm.fit(Z, data['Deaths - cumulative total'])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [42]:
lm.intercept_

8226.382573874616

In [43]:
lm.coef_

array([ 0.03021472, -0.61046519])

In [44]:
lm.fit(Z, data['Deaths - cumulative total'])
print('The R-square is: ', lm.score(Z, data['Deaths - cumulative total']))

The R-square is:  0.8885955095649392


In [45]:
Y_predict_multifit = lm.predict(Z)

In [56]:
print('The mean square error of price and predicted value using multifit is: ', \
      mean_squared_error(data['Deaths - cumulative total'], Y_predict_multifit))

The mean square error of price and predicted value using multifit is:  1463057247.144048


In [57]:
from scipy import stats

In [58]:
pearson_coef, p_value = stats.pearsonr(data['Deaths - cumulative total'], data['Cases - cumulative total'])
print("The Pearson Correlation Coefficient is", pearson_coef, " with a P-value of P =", p_value)

The Pearson Correlation Coefficient is 0.9379400604120807  with a P-value of P = 1.6772550130122968e-26


In [59]:
from sklearn.preprocessing import StandardScaler
X_initial = X
scaler = preprocessing.StandardScaler().fit(X_initial)
X= scaler.transform(X)
X[0:12]

array([[ 6.70733462],
       [ 2.50672632],
       [ 0.72835567],
       [ 0.46765465],
       [ 0.94449019],
       [-0.15441879],
       [-0.17775457],
       [-0.22532668],
       [-0.21600588],
       [-0.20039241],
       [-0.22546176],
       [-0.18900032]])

In [70]:
data[['Deaths - cumulative total','Cases - cumulative total','Cases - newly reported in last 7 days','Cases - newly reported in last 24 hours']].head()

Deaths - cumulative total  ...  Cases - newly reported in last 24 hours
0                     609022  ...                                    78722
1                     557223  ...                                    15143
2                     106045  ...                                    11183
3                     121216  ...                                     6636
4                     241279  ...                                     6506

[5 rows x 4 columns]